" Vim color file - candycode_bluecursorline
" Generated by http://bytefluent.com/vivify 2021-01-11
set background=dark
if version > 580
	hi clear
	if exists("syntax_on")
		syntax reset
	endif
endif

set t_Co=256
let g:colors_name = "candycode_bluecursorline"

"hi CTagsMember -- no settings --
"hi CTagsGlobalConstant -- no settings --
hi Normal guifg=#ffffff guibg=#050505 guisp=#050505 gui=NONE ctermfg=15 ctermbg=232 cterm=NONE
"hi CTagsImport -- no settings --
"hi CTagsGlobalVariable -- no settings --
"hi SpellRare -- no settings --
"hi EnumerationValue -- no settings --
"hi Float -- no settings --
"hi Union -- no settings --
"hi VisualNOS -- no settings --
"hi EnumerationName -- no settings --
"hi SpellCap -- no settings --
"hi SpellLocal -- no settings --
"hi DefinedName -- no settings --
"hi LocalVariable -- no settings --
"hi SpellBad -- no settings --
"hi CTagsClass -- no settings --
"hi clear -- no settings --
hi IncSearch guifg=#000000 guibg=#eedd33 guisp=#eedd33 gui=bold ctermfg=NONE ctermbg=227 cterm=bold
hi WildMenu guifg=#ffffff guibg=#133293 guisp=#133293 gui=bold ctermfg=15 ctermbg=18 cterm=bold
hi SignColumn guifg=#c8bcb9 guibg=#786d65 guisp=#786d65 gui=bold ctermfg=251 ctermbg=95 cterm=bold
hi SpecialComment guifg=#9999aa guibg=NONE guisp=NONE gui=bold ctermfg=103 ctermbg=NONE cterm=bold
hi Typedef guifg=#4093cc guibg=NONE guisp=NONE gui=bold ctermfg=74 ctermbg=NONE cterm=bold
hi Title guifg=#dd4452 guibg=NONE guisp=NONE gui=bold ctermfg=167 ctermbg=NONE cterm=bold
hi Folded guifg=#c2bfa5 guibg=#050505 guisp=#050505 gui=underline ctermfg=187 ctermbg=232 cterm=underline
hi PreCondit guifg=#bb88dd guibg=NONE guisp=NONE gui=NONE ctermfg=140 ctermbg=NONE cterm=NONE
hi Include guifg=#bb88dd guibg=NONE guisp=NONE gui=NONE ctermfg=140 ctermbg=NONE cterm=NONE
hi TabLineSel guifg=#ffffff guibg=#133293 guisp=#133293 gui=NONE ctermfg=15 ctermbg=18 cterm=NONE
hi StatusLineNC guifg=#444444 guibg=#c2bfa5 guisp=#c2bfa5 gui=NONE ctermfg=238 ctermbg=187 cterm=NONE
hi NonText guifg=#77ff22 guibg=NONE guisp=NONE gui=bold ctermfg=82 ctermbg=NONE cterm=bold
hi DiffText guifg=#ffffff guibg=#976398 guisp=#976398 gui=bold ctermfg=15 ctermbg=96 cterm=bold
hi ErrorMsg guifg=#ffffff guibg=#ff0000 guisp=#ff0000 gui=bold ctermfg=15 ctermbg=196 cterm=bold
hi Ignore guifg=#888888 guibg=NONE guisp=NONE gui=NONE ctermfg=102 ctermbg=NONE cterm=NONE
hi Debug guifg=#9999aa guibg=NONE guisp=NONE gui=bold ctermfg=103 ctermbg=NONE cterm=bold
hi PMenuSbar guifg=NONE guibg=#555555 guisp=#555555 gui=NONE ctermfg=NONE ctermbg=240 cterm=NONE
hi Identifier guifg=#eecc44 guibg=NONE guisp=NONE gui=NONE ctermfg=221 ctermbg=NONE cterm=NONE
hi SpecialChar guifg=#9999aa guibg=NONE guisp=NONE gui=bold ctermfg=103 ctermbg=NONE cterm=bold
hi Conditional guifg=#4093cc guibg=NONE guisp=NONE gui=bold ctermfg=74 ctermbg=NONE cterm=bold
hi StorageClass guifg=#4093cc guibg=NONE guisp=NONE gui=bold ctermfg=74 ctermbg=NONE cterm=bold
hi Todo guifg=#ffffff guibg=#ee7700 guisp=#ee7700 gui=bold ctermfg=15 ctermbg=208 cterm=bold
hi Special guifg=#9999aa guibg=NONE guisp=NONE gui=bold ctermfg=103 ctermbg=NONE cterm=bold
hi LineNr guifg=#928c75 guibg=NONE guisp=NONE gui=NONE ctermfg=101 ctermbg=NONE cterm=NONE
hi StatusLine guifg=#000000 guibg=#c2bfa5 guisp=#c2bfa5 gui=bold ctermfg=NONE ctermbg=187 cterm=bold
hi Label guifg=#4093cc guibg=NONE guisp=NONE gui=bold ctermfg=74 ctermbg=NONE cterm=bold
hi PMenuSel guifg=#ffffff guibg=#133293 guisp=#133293 gui=NONE ctermfg=15 ctermbg=18 cterm=NONE
hi Search guifg=#efefd0 guibg=#937340 guisp=#937340 gui=NONE ctermfg=230 ctermbg=137 cterm=NONE
hi Delimiter guifg=#9999aa guibg=NONE guisp=NONE gui=bold ctermfg=103 ctermbg=NONE cterm=bold
hi Statement guifg=#66d077 guibg=NONE guisp=NONE gui=bold ctermfg=77 ctermbg=NONE cterm=bold
hi Comment guifg=#ff9922 guibg=NONE guisp=NONE gui=NONE ctermfg=208 ctermbg=NONE cterm=NONE
hi Character guifg=#ff6050 guibg=NONE guisp=NONE gui=NONE ctermfg=203 ctermbg=NONE cterm=NONE
hi Number guifg=#ff6050 guibg=NONE guisp=NONE gui=NONE ctermfg=203 ctermbg=NONE cterm=NONE
hi Boolean guifg=#ff6050 guibg=NONE guisp=NONE gui=bold ctermfg=203 ctermbg=NONE cterm=bold
hi Operator guifg=#4093cc guibg=NONE guisp=NONE gui=bold ctermfg=74 ctermbg=NONE cterm=bold
hi CursorLine guifg=#3797c7 guibg=#1b1b1b guisp=#1b1b1b gui=NONE ctermfg=74 ctermbg=234 cterm=NONE
hi TabLineFill guifg=#000000 guibg=#c2bfa5 guisp=#c2bfa5 gui=NONE ctermfg=NONE ctermbg=187 cterm=NONE
hi Question guifg=#66d077 guibg=NONE guisp=NONE gui=NONE ctermfg=77 ctermbg=NONE cterm=NONE
hi WarningMsg guifg=#ccae22 guibg=NONE guisp=NONE gui=bold ctermfg=178 ctermbg=NONE cterm=bold
hi DiffDelete guifg=#000000 guibg=#be1923 guisp=#be1923 gui=bold ctermfg=NONE ctermbg=1 cterm=bold
hi ModeMsg guifg=#eecc18 guibg=NONE guisp=NONE gui=NONE ctermfg=220 ctermbg=NONE cterm=NONE
hi CursorColumn guifg=NONE guibg=#1b1b1b guisp=#1b1b1b gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
hi Define guifg=#bb88dd guibg=NONE guisp=NONE gui=NONE ctermfg=140 ctermbg=NONE cterm=NONE
hi Function guifg=#eecc44 guibg=NONE guisp=NONE gui=NONE ctermfg=221 ctermbg=NONE cterm=NONE
hi FoldColumn guifg=#c8bcb9 guibg=#786d65 guisp=#786d65 gui=bold ctermfg=251 ctermbg=95 cterm=bold
hi PreProc guifg=#bb88dd guibg=NONE guisp=NONE gui=NONE ctermfg=140 ctermbg=NONE cterm=NONE
hi Visual guifg=#ffffff guibg=#606070 guisp=#606070 gui=NONE ctermfg=15 ctermbg=242 cterm=NONE
hi MoreMsg guifg=#39d049 guibg=NONE guisp=NONE gui=NONE ctermfg=77 ctermbg=NONE cterm=NONE
hi VertSplit guifg=#c2bfa5 guibg=#c2bfa5 guisp=#c2bfa5 gui=NONE ctermfg=187 ctermbg=187 cterm=NONE
hi Exception guifg=#4093cc guibg=NONE guisp=NONE gui=bold ctermfg=74 ctermbg=NONE cterm=bold
hi Keyword guifg=#4093cc guibg=NONE guisp=NONE gui=bold ctermfg=74 ctermbg=NONE cterm=bold
hi Type guifg=#4093cc guibg=NONE guisp=NONE gui=bold ctermfg=74 ctermbg=NONE cterm=bold
hi DiffChange guifg=#000000 guibg=#976398 guisp=#976398 gui=NONE ctermfg=NONE ctermbg=96 cterm=NONE
hi Cursor guifg=#000000 guibg=#ffff99 guisp=#ffff99 gui=NONE ctermfg=NONE ctermbg=228 cterm=NONE
hi Error guifg=#ffffff guibg=#ff0000 guisp=#ff0000 gui=NONE ctermfg=15 ctermbg=196 cterm=NONE
hi PMenu guifg=#000000 guibg=#a6a190 guisp=#a6a190 gui=NONE ctermfg=NONE ctermbg=144 cterm=NONE
hi SpecialKey guifg=#559933 guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
hi Constant guifg=#ff6050 guibg=NONE guisp=NONE gui=NONE ctermfg=203 ctermbg=NONE cterm=NONE
hi Tag guifg=#9999aa guibg=NONE guisp=NONE gui=bold ctermfg=103 ctermbg=NONE cterm=bold
hi String guifg=#ff6050 guibg=NONE guisp=NONE gui=NONE ctermfg=203 ctermbg=NONE cterm=NONE
hi PMenuThumb guifg=NONE guibg=#cccccc guisp=#cccccc gui=NONE ctermfg=NONE ctermbg=252 cterm=NONE
hi MatchParen guifg=NONE guibg=#3377aa guisp=#3377aa gui=NONE ctermfg=NONE ctermbg=67 cterm=NONE
hi Repeat guifg=#4093cc guibg=NONE guisp=NONE gui=bold ctermfg=74 ctermbg=NONE cterm=bold
hi Directory guifg=#00bbdd guibg=NONE guisp=NONE gui=NONE ctermfg=38 ctermbg=NONE cterm=NONE
hi Structure guifg=#4093cc guibg=NONE guisp=NONE gui=bold ctermfg=74 ctermbg=NONE cterm=bold
hi Macro guifg=#bb88dd guibg=NONE guisp=NONE gui=NONE ctermfg=140 ctermbg=NONE cterm=NONE
hi Underlined guifg=#80a0ff guibg=NONE guisp=NONE gui=underline ctermfg=12 ctermbg=NONE cterm=underline
hi DiffAdd guifg=#ffffff guibg=#126493 guisp=#126493 gui=NONE ctermfg=15 ctermbg=24 cterm=NONE
hi TabLine guifg=#000000 guibg=#c2bfa5 guisp=#c2bfa5 gui=NONE ctermfg=NONE ctermbg=187 cterm=NONE
hi cursorim guifg=#000000 guibg=#aaccff guisp=#aaccff gui=NONE ctermfg=NONE ctermbg=153 cterm=NONE
hi underline guifg=#afafff guibg=NONE guisp=NONE gui=NONE ctermfg=147 ctermbg=NONE cterm=NONE
